### ISSUE TITLE
Strange animation behaviour of styleguide menu when switching between sections

### ISSUE THREAD

**Issue by MrFirthy** [tangentsnowball/house-styles#43]
If you take a look at the styleguide on a mobile device, opening the menu behaves as expected. However switching to another section, or closing the menu manually, causes a strange issue where the main content doesn't move back over to fill the screen in the same way. Instead, it appears to 'grow' from the top right hand corner.

**Comment by ecobbold15** [comment]
Plan to fix this with a new menu - current implementation is more of a 'better-than-the-last-one-at-least' affair
