### ISSUE TITLE
General discussion: Thoughts on adding Fastclick to core vendor file of house styles

### ISSUE THREAD

**Issue by MrFirthy** [tangentsnowball/house-styles#44]
http://labs.ft.com/articles/ft-fastclick/

Seems to work pretty well. What are you thoughts on this?

**Comment by ecobbold15** [comment]
Looks interesting - I can't relly test out how well it works as I'm not an iOS guy (perhaps you can see a difference), but if it improves QoL significantly for iOS users then it might be an idea. The delay and focus issues don't seem to be a thing on Android.

If it changes the way we implement all buttons in the future just to cater for iOS though, then we'd be in the same boat as making IE-specific fixes - which is a boat we're always trying to escape from. :(

I'll leave this one up to you.

**Comment by MrFirthy** [comment]
Oh really? I couldn't test in on Android so that's interesting to know. Could you not see any difference in speed on your Android device in their first demo?

It shouldn't change anything about our current implementation as it's quite one event handler that gets attached to the body on page load. I will make a speculative branch at some point and we can test/discuss it properly when I'm back.

**Comment by ecobbold15** [comment]
Yeah I don't notice any difference on Android, both with the crappy stock browser nor with Chrome. You have an iPhone right? Is it noticeable?

**Comment by MrFirthy** [comment]
Yeah, on both Safari and Chrome you can see the 300ms delay on buttons that they talk about, so I'm guessing it's just an iPhone thing regarding how they interpret taps into clicks.
