### ISSUE TITLE
Move third party dependencies that aren't core files into static/dist/js/vendor

### ISSUE THREAD

**Issue by MrFirthy** [tangentsnowball/house-styles#45]
I know we didn't get a chance to do this Friday evening and you said it was a fairly routine change. Drop a comment in here if there are any issues.

**Comment by ecobbold15** [comment]
The solution I have in mind is to have the bower:js task drop all non-core js libs into the js.dest folder just as they are. If MBF is grabbing the wrong files, we can simply override what it grabs by passing some extra overrides config.

This assumes that
- The current method for concatenating 'core' vendor JS libs into `vendor.js` will remain unchanged, though perhaps renamed - e.g. `vendor-core.js`
- The generation of ie8 vendor JS is a bit 'special' (lol) and needs to be on every page anyway, so we'll also keep that as `ie8.js` and maintain handling those separately

So, the process will likely be
- Predefine a list of core libs alongside the paths, etc. as an array of names as strings
- Use core lib names in a glob pattern to filter the core libs out from the mainBowerFiles JS stream
- Plop these out to `static/dist/js/vendor`

**Comment by MrFirthy** [comment]
That all sounds good to me. I think having the core files as `core.min.js` inside the vendor folder is neat.
